#!/bin/bash

entrada=$1;
saida=$2
bits=$3

if [ $# -lt 3 ]; then # caso nao tenha "3" argumentos faça 
	echo "[Not arguments]";
	echo "[Example _nasm file.asm file 64]"
else # se nao ...
		echo "![##########]50%"
		nasm -f elf$bits $entrada -o a.out # compilar assembly
		echo "![################]60%"
		ld a.out -o $saida # linkar asm
		echo "![#####################]100%" # compilado
		./$saida
fi
