#!/bin/sh

file=$1
out=$2

[ $# -lt 2 ] &&	echo "Need more arguments!" && \
             echo "Usage: $0 <file.asm> <output.out> " && \
	     echo "E.g.: $0 hello.asm hello.out" && \
	     exit

# Set the default architecture to x86
nasm -f elf_i386 $file
ld a.out -o $out
rm a.out
echo "\033[32m[+]\033[0m Done!"
